# Generated by Django 3.2.5 on 2021-07-10 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumCounter',
            fields=[
                ('counter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('my_user_id', models.PositiveIntegerField(default=100000)),
                ('my_article_id', models.PositiveIntegerField(default=1100000)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('my_user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.PositiveSmallIntegerField(default=0)),
                ('photo_url', models.ImageField(blank=True, upload_to='')),
                ('address_provinces', models.CharField(blank=True, max_length=10)),
                ('address_city', models.CharField(blank=True, max_length=10)),
                ('habits1', models.CharField(blank=True, max_length=10)),
                ('habits2', models.CharField(blank=True, max_length=10)),
                ('habits3', models.CharField(blank=True, max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('signature', models.CharField(default='还没有个性签名呢~', max_length=50)),
                ('exp_value', models.PositiveIntegerField(default=1)),
                ('front_size', models.IntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
