# Generated by Django 3.2.5 on 2021-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numcounter',
            name='my_comment_id',
            field=models.PositiveIntegerField(default=20000),
        ),
    ]
