# Generated by Django 3.2.5 on 2021-07-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_numcounter_my_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile',
            field=models.IntegerField(default=0),
        ),
    ]
