# Generated by Django 3.2.5 on 2021-07-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_myuser_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='audio_person',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='myuser',
            name='audio_pitch',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='myuser',
            name='audio_speed',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='myuser',
            name='audio_volume',
            field=models.IntegerField(default=5),
        ),
    ]
