# Generated by Django 3.2.5 on 2021-07-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_time']},
        ),
        migrations.AddField(
            model_name='article',
            name='article_type1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='article_type2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='article_type3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
