# Generated by Django 3.2.5 on 2021-07-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='audioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PER', models.IntegerField()),
                ('SPD', models.IntegerField()),
                ('PIT', models.IntegerField()),
                ('VOL', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_chose_audio',
            field=models.BooleanField(default=True),
        ),
    ]
