# Generated by Django 3.2.5 on 2021-07-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_chose_audio',
            field=models.BooleanField(default=True),
        ),
    ]
