# Generated by Django 3.2.5 on 2021-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210711_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeListComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
