# Generated by Django 3.2.5 on 2021-07-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20210715_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_audio',
        ),
    ]
