# Generated by Django 3.2.5 on 2021-07-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_remove_comment_comment_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_audio',
            field=models.IntegerField(default=-1),
        ),
    ]
