# Generated by Django 3.2.5 on 2021-07-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_article_article_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_person',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='article',
            name='audio_pitch',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='article',
            name='audio_speed',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='article',
            name='audio_volume',
            field=models.IntegerField(default=5),
        ),
    ]
